import {ThermalRuntime} from '../thermal-runtime.ts';
import {ThermalModel,makeThermalGrid,DEFAULT_THERMAL} from '../thermal.ts';
import {WaterModel,DEFAULT_WATER,moistureCapacity} from '../water.ts';
import {DEFAULT_PLANET} from '../planet.ts';
import {DEFAULT_ORBIT} from '../astronomy.ts';
import {weatherFields} from '../weather.ts';
const output=document.querySelector('pre')!,check=(ok:boolean,message:string)=>{if(!ok)throw new Error(message);};
function figure(parent:string,label:string){const f=document.createElement('figure'),cap=document.createElement('figcaption');cap.textContent=label;f.append(cap);document.querySelector('#'+parent)!.append(f);return f;}
function image(parent:string,name:string,label:string,folder:string){const f=figure(parent,label),img=document.createElement('img');img.src=`../${folder}/${name}.png`;f.prepend(img);return img.decode();}
function map(parent:string,label:string,g:ReturnType<typeof makeThermalGrid>,field:ArrayLike<number>,limit:number){
    const f=figure(parent,label),c=document.createElement('canvas');c.width=560;c.height=315;f.prepend(c);const ctx=c.getContext('2d')!,left=38,top=12,width=508,height=260;ctx.fillStyle='#10202a';ctx.fillRect(0,0,c.width,c.height);
    for(let y=0;y<height;y++)for(let x=0;x<g.width;x++){const row=Math.min(g.height-1,Math.floor((1-Math.cos(Math.PI*(y+.5)/height))/2*g.height)),a=Math.max(0,Math.min(1,field[row*g.width+x]/limit));ctx.fillStyle=`rgb(${Math.round(20+217*a)},${Math.round(45+197*a)},${Math.round(66+181*a)})`;ctx.fillRect(left+x/g.width*width,top+y,Math.ceil(width/g.width),1);}
    ctx.strokeStyle='#a1bcc6';ctx.strokeRect(left,top,width,height);ctx.font='12px system-ui';ctx.fillStyle='#c0d6de';for(const lat of [60,0,-60])ctx.fillText(`${lat}°`,0,top+(90-lat)/180*height+4);ctx.fillText('−180°',left,top+height+20);ctx.fillText('0°',left+width/2-8,top+height+20);ctx.fillText('+180°',left+width-38,top+height+20);ctx.fillText(`dark 0 → white ${limit}${limit===100?'%':''}; higher values saturate`,left,top+height+38);
}
try{
    const folder=new URLSearchParams(location.search).get('folder')||'build/validation/weather';const docs=await Promise.all(['initial','saved','all-systems'].map(async name=>{const r=await fetch(`../${folder}/${name}.json`);check(r.ok,'Missing downloaded state');return r.json();}));
    const rt=docs.map(d=>ThermalRuntime.fromSnapshot(d.runtime,d.terrain.settings.planet,d.terrain.settings.orbit)),fields=rt.map(r=>weatherFields(r.model!,r.water!));
    const mean=(f:ArrayLike<number>)=>Array.from(f).reduce((a,b)=>a+b,0)/f.length,age=(r:ThermalRuntime)=>(r.model!.timeS-r.model!.epochS)/86400;
    document.querySelector('#configuration')!.textContent=`Seed ${docs[0].terrain.parameters.elevation.seed}; Earth radius ${(docs[0].terrain.settings.planet.radiusM/1000).toFixed(4)} km; 48 × 24 cells; same Surface camera; dynamic circulation enabled. No decorative weather clock.`;
    for(const [index,parent,prefix] of [[0,'zero-pair','zero'],[1,'evolved-pair','day49']] as const){for(const on of [false,true])await image(parent,`${prefix}-${on?'cloud':'clear'}`,`${age(rt[index]).toFixed(6)} d · cloud ${on?'on':'off'} · mean proxy ${(100*mean(fields[index].cloud)).toFixed(2)}%`,folder);map('fields',`${age(rt[index]).toFixed(6)} d · column saturation, 0–1`,rt[index].grid,fields[index].saturation,1);map('fields',`${age(rt[index]).toFixed(6)} d · cloud proxy, 0–100%`,rt[index].grid,fields[index].cloud.map(v=>v*100),100);}
    const budgets={water:rt[2].water!.diagnostics().residualMm,energy:rt[2].environment!.diagnostics().energyResidualJm2,solid:rt[2].water!.glacier!.diagnostics().solidResidualM};
    check(Math.abs(budgets.water)<1e-6&&Math.abs(budgets.energy)<1e-4&&Math.abs(budgets.solid)<1e-10,'Coupled budgets');
    document.querySelector('#coupled-config')!.textContent=`Age ${age(rt[2]).toFixed(6)} d since reset (epoch day ${(rt[2].model!.epochS/86400).toFixed(6)}). Water ${budgets.water.toExponential(3)} mm; enthalpy ${budgets.energy.toExponential(3)} J/m²; solid ${budgets.solid.toExponential(3)} m. PNG pair byte-equal.`;
    await image('restore-pair','coupled-before','Downloaded world · native reload 1',folder);await image('restore-pair','coupled-reloaded','Same downloaded world · native reload 2',folder);
    for(const [parent,prefix,title] of [['north','north','North pole'],['south','south','South pole'],['seam','seam','Longitude seam']] as const)for(const suffix of ['a','b'])await image(parent,`${prefix}-${suffix}`,`${title} · pose ${suffix}`,folder);
    await image('precipitation-pair','precipitation','Production layer: 0–20 mm/day; higher values saturate',folder);await image('precipitation-pair','precipitation-readout','Inspect: total, liquid remainder, recorded land snowfall and sample time',folder);
    document.querySelector('#precipitation-values')!.textContent=`Day ${age(rt[1]).toFixed(6)}: mean total ${mean(fields[1].precipitationMmDay).toFixed(6)} mm/day; liquid remainder ${mean(fields[1].rainMmDay).toFixed(6)}; land snowfall ${mean(fields[1].snowMmDay).toFixed(6)}. Latest step ends at absolute day ${(rt[1].model!.timeS/86400).toFixed(6)}.`;
    const grid=makeThermalGrid(8,4),land=new Float64Array(grid.count),m=new ThermalModel(DEFAULT_PLANET,DEFAULT_ORBIT,DEFAULT_THERMAL,land,0,grid);m.temperatureK.fill(290);const w=new WaterModel(grid,DEFAULT_PLANET.radiusM,land,new Float64Array(grid.count),m.temperatureK,{...DEFAULT_WATER,evaporationFraction:0,moistureDiffusivityM2s:0});
    w.atmosphereKgM2.fill(.85*moistureCapacity(290));map('temperature-fields','Fixed water: 290 K everywhere',grid,weatherFields(m,w).cloud.map(v=>100*v),100);for(let i=0;i<grid.count;i++)m.temperatureK[i]=i%8<4?280:300;const local=weatherFields(m,w);check(local.cloud[0]===1&&local.cloud[4]===0,'Temperature response');map('temperature-fields','Same water: left 280 K / right 300 K',grid,local.cloud.map(v=>100*v),100);
    m.temperatureK.fill(290);w.atmosphereKgM2.fill(0);w.atmosphereKgM2[8]=.95*moistureCapacity(290);const total=w.total();map('transport-fields','Initial column water (kg/m²); source cell 8',grid,w.atmosphereKgM2,22);w.setWinds(new Float64Array(grid.count).fill(10),new Float64Array(grid.count));for(let i=0;i<12;i++)w.step(w.maxStepS,m.temperatureK,new Float64Array(grid.count));check(w.atmosphereKgM2[9]>0&&Math.abs(w.total()-total)<1e-7,'Conserved eastward transport');map('transport-fields','After 12 stable steps: actual eastward transport',grid,w.atmosphereKgM2,22);document.querySelector('#controlled-values')!.textContent=`Earth radius; east wind 10 m/s; ${(w.elapsedS/86400).toFixed(6)} d. Downwind cell 9 water ${w.atmosphereKgM2[9].toFixed(6)} kg/m²; global water change ${(w.total()-total).toExponential(3)} mm. No extra water was added to make the pattern visible.`;
    output.textContent=JSON.stringify({status:'PASS',ages:rt.map(age),cloudMeans:fields.map(f=>mean(f.cloud)),precipitationMean:mean(fields[1].precipitationMmDay),snowfallMean:mean(fields[1].snowMmDay),budgets,controlled:{elapsedS:w.elapsedS,downwindKgM2:w.atmosphereKgM2[9],waterChangeMm:w.total()-total}},null,2);
}catch(error){output.textContent=JSON.stringify({status:'FAIL',error:String(error)},null,2);}
