// Presentation vocabulary for this Chinese scene. Simulation identifiers and
// saved JSON remain unchanged; scientific symbols retain their standard units.
const labels={
  'Planet physics':'行星物理','View':'观察方式','Follow surface':'跟随地表','From space':'太空视角',
  'Live planet':'实时演化','Generate climate now':'立即生成气候','Compare environment…':'环境对比',
  'Play':'播放','Pause':'暂停','Time speed':'时间速度','1 minute / second':'每秒推进 1 分钟',
  '1 hour / second':'每秒推进 1 小时','1 day / second':'每秒推进 1 天','10 days / second':'每秒推进 10 天',
  'Elapsed time (days)':'已运行时间（天）','Spin phase (°)':'自转相位（°）','Season phase (°)':'季节相位（°）',
  'Reset time':'重置时间','Inspect: off':'查看地表信息','Inspect: on':'地表查看：已开启',
  'Inspect a surface point to read its location and solar energy.':'开启后点击地球，查看位置、海拔、气候和水流。',
  'No terrain here. Select a point on the globe.':'此处没有地形，请点击地球表面。',
  'Physical size':'大小与重力','Radius (km)':'行星半径（千米）','Mean density (kg/m³)':'平均密度（千克/立方米）',
  'Mass':'质量','Surface gravity':'地表重力','Escape speed':'逃逸速度','Rotation & solar orbit':'自转与公转',
  'Sidereal day (hours)':'恒星日（小时）','Axial tilt (°)':'自转轴倾角（°）','Retrograde spin':'逆向自转',
  'Orbit distance (AU)':'轨道距离（天文单位）','Bond albedo':'邦德反照率','Orbital year':'公转周期',
  'Mean solar day':'平均太阳日','No mean solar cycle':'无平均太阳日周期','Physical terrain scale':'物理地形尺度',
  'Land height scale (km)':'陆地高程尺度（千米）','Seafloor scale (km)':'海底深度尺度（千米）',
  'Display exaggeration':'显示高度夸张倍数','Radiation reference':'辐射参考','Stellar irradiance':'恒星辐照度',
  'Radiative Teq':'辐射平衡温度','Earth preset':'恢复地球物理参数',
  'Seasonal temperature':'气温与四季','Enable thermal model':'启用温度模型','Global mean':'全球平均气温',
  'Temperature range':'气温范围','Time since thermal reset':'本轮温度演化时间','Thermal parameters':'温度模型参数',
  'Effective IR emissivity (0.1–1)':'有效红外发射率（0.1–1）',
  'Land heat capacity (MJ/m²/K)':'陆地热容量（MJ/m²/K）','Ocean mixed-layer depth (m)':'海洋混合层深度（米）',
  'Heat transport at Earth radius (W/m²/K)':'地球半径下的热输送（W/m²/K）','Reset temperature & water':'重置温度与水循环',
  'Water cycle':'水循环','Enable water cycle':'启用水循环','Mean precipitation':'平均降水','Mean land snowfall':'平均陆地降雪',
  'Mean evaporation':'平均蒸发','Atmosphere / soil / surface':'大气 / 土壤 / 地表蓄水','Ocean inventory':'海洋储水量',
  'Water budget residual':'水量守恒残差','Largest cell outflow':'最大网格流出量','Time since water reset':'本轮水循环演化时间',
  'Water parameters':'水循环参数','Evaporation energy fraction (0–1)':'蒸发能量比例（0–1）',
  'Soil capacity (mm per land area)':'土壤容量（陆地毫米水深）','Initial ocean water depth (m)':'初始海洋水深（米）',
  'Wind belt strength (m/s; negative reverses)':'风带强度（米/秒；负值反向）','Vapor mixing (m²/s)':'水汽混合（m²/s）',
  'Surface travel speed (m/s)':'地表水流速（米/秒）','Ice, ocean & vegetation':'冰雪、海流与植被',
  'Ocean circulation strength (m/s)':'海流强度（米/秒）','Evolving wind & ocean circulation':'动态大气与海洋环流',
  'Cloud cover on Planet surface':'显示云层','Evolve vegetation & feedback':'植被演化与反馈','Ice / snow albedo feedback':'冰雪反照率反馈',
  'Grounded ice flow & glacial erosion':'陆地冰川流动与侵蚀','Terrain rivers, lakes & wetlands':'地形河流、湖泊与湿地',
  'Snow / sea-ice inventory':'积雪 / 海冰储量','Snow / land-ice melt':'积雪 / 陆冰融化','Combined energy residual':'总能量守恒残差',
  'Erosion & deposition preview':'侵蚀与沉积','Capture current water':'采集当前水流','Capture glacial erosion':'采集冰川侵蚀',
  'Years per click (requested)':'单次演化年数','Evolve terrain':'演化地形','Undo last evolve':'撤销上次演化',
  'Preview geometry':'显示地形预览','Reset erosion preview':'重置侵蚀预览','Apply erosion to terrain':'将侵蚀应用到地形',
  'Geological time':'地质演化时间','Net height change':'净高度变化','Mobile / ocean sediment':'搬运中 / 入海沉积物',
  'Solid budget residual':'固体守恒残差','Erosion parameters':'侵蚀参数','Incision coefficient (m/yr)':'下切系数（米/年）',
  'Slope smoothing (m²/yr)':'坡面平滑（m²/年）','Sediment settling time (yr)':'沉积物沉降时间（年）',
  'Save & restore world':'保存与恢复','Undo last application':'撤销上次地形应用','Download complete simulation':'下载完整模拟',
  'Download terrain JSON':'下载地形文件','Load simulation / terrain JSON':'载入模拟或地形文件',
  'Reading saved world…':'正在读取存档…','Preparing saved world…':'正在准备存档…',
  'Rebuilding terrain and rivers…':'正在重建地形与河流…','Terrain ready':'地形已就绪','No applied erosion layer.':'尚未应用侵蚀。',
  'Complete simulation restored, paused at the saved moment. Press Play to continue.':'完整模拟已恢复，并暂停在存档时刻；点击播放继续。',
  'Complete simulation downloaded. Unapplied erosion preview and undo history are excluded.':'完整模拟已下载；不包含尚未应用的侵蚀预览及撤销记录。',
  'Terrain document downloaded. Climate and preview are excluded.':'地形文件已下载；不包含气候状态及预览。',
  'Load canceled because newer edits were made.':'载入已取消：读取期间发生了新的编辑。',
  'Load canceled because newer edits or time changes were made.':'载入已取消：准备期间发生了新的编辑或时间变化。',
  'Wait for terrain generation':'请等待地形生成完成','Simulation file exceeds 32 MiB':'模拟文件超过 32 MiB 上限',
  'Reset':'重置地形','Drag: Paint':'拖动：绘制地形','Drag: Rotate':'拖动：旋转地球',
  'Ocean':'深海','Water':'浅水','Valley':'平原 / 山谷','Mountain':'山脉','Mountains':'山脉',
  'elevation':'地形生成参数','biomes':'地表生成参数','rivers':'参考河网参数','render':'高级画面参数',
  'seed':'随机种子','island':'岛屿比例','noisy_coastlines':'海岸曲折度','hill_height':'丘陵高度',
  'mountain_jagged':'山脉崎岖度','mountain_sharpness':'山峰锐度','mountain_folds':'山脉褶皱',
  'ocean_depth':'海底深度','wind_angle_deg':'风向角','raininess':'降雨强度','rain_shadow':'雨影效应','evaporation':'蒸发强度',
  'lg_min_flow':'最小显示流量（对数）','lg_river_width':'河宽（对数）','flow':'参考径流强度',
  'sphere_radius':'画面球体半径','zoom':'缩放','x':'水平视角','y':'垂直视角','light_angle_deg':'光照方向',
  'slope':'坡面明暗','flat':'平坦区域亮度','ambient':'环境光','overhead':'顶光强度','tilt_deg':'画面倾斜角',
  'rotate_deg':'画面旋转角','mountain_height':'地形显示高度','outline_depth':'轮廓深度','outline_strength':'轮廓强度',
  'outline_threshold':'轮廓阈值','outline_coast':'海岸轮廓','outline_water':'水面轮廓','biome_colors':'地表色彩',
  'Perennial ice / snow':'常年冰雪','Tundra':'苔原','Boreal forest':'寒带针叶林','Temperate forest':'温带森林',
  'Grassland / steppe':'草原','Desert':'荒漠','Savanna':'稀树草原','Tropical seasonal forest':'热带季雨林',
  'Tropical rainforest':'热带雨林','Barren ground':'裸地','Grounded ice':'陆地冰川','Sea ice':'海冰',
  'Off':'已关闭','Unavailable':'暂无数据','Phase unavailable':'暂无雨雪相态数据','No snapshot':'尚未采集',
  'Enable water':'请启用水循环','Thermal model off':'温度模型已关闭','Water model off':'水循环已关闭','Waiting for terrain':'正在等待地形',
  'Enable water, then capture a snapshot.':'请启用水循环，再采集水流快照。',
  'Enable Water cycle or select a water layer before capture.':'采集前请启用水循环，或选择水流图层。',
  'Preview reset. Authored terrain is unchanged.':'预览已重置，原地形保持不变。',
  'Source terrain/environment changed. Capture a new water snapshot.':'地形或环境已变化，请重新采集水流快照。',
  'Water model unavailable. Enable water and use a supported rotation.':'水循环不可用，请启用水循环并使用模型支持的自转速度。',
  'Snapshot captured. Geological time advances only with Evolve.':'水流已采集；点击「演化地形」才会推进地质时间。',
  'Enable grounded ice before capturing glacial erosion.':'采集冰川侵蚀前，请启用陆地冰川。',
  'Previous geological step restored.':'已恢复上一次地质演化状态。',
  'Erosion parameters changed. Capture a new water snapshot.':'侵蚀参数已改变，请重新采集水流快照。',
  'Erosion applied. Rivers and environment are being rebuilt.':'侵蚀已应用，正在重建河流与环境。',
  'Environment comparison':'环境对比','Generated baseline → evolving planet':'初始基准 → 当前演化状态','Close':'关闭',
  'Close comparison':'关闭环境对比','Use current as baseline':'设为对比基准','Export comparison CSV':'导出对比表格',
  'Map':'图层','Planet surface':'地球地表','Temperature':'气温','Snow water equivalent':'积雪水当量',
  'Sea-ice thickness':'海冰厚度','Grounded ice thickness':'陆冰厚度','Vegetation cover':'植被覆盖','Ocean currents':'海流',
  'Baseline':'基准','Current':'当前','Budgets & coverage':'守恒与覆盖率','Metric':'指标',
  'Temperature by latitude':'各纬度气温','Evolution since generation':'本轮演化过程','Captured parameters':'采集时的参数',
  'Baseline global map':'基准全球图','Current global map':'当前全球图','Latitude temperature profiles':'纬度气温曲线',
  'Time history of snow, ice and vegetation coverage':'冰雪与植被覆盖率的时间变化',
  'Move over either map to compare the same location. North is at the top; longitude wraps at the edges.':'鼠标移到任一地图，比较同一地点。上方为北，两侧经度相接。',
  'Baseline dashed gold · Current cyan · longitude mean, °C':'金色虚线：基准；青色：当前。数值为各纬度的经向平均气温（°C）。',
  'Ocean ice cyan · Land snow white · Vegetation green · coverage 0–100%':'青色：海冰；白色：陆地积雪；绿色：植被。覆盖率 0–100%。',
  'Editable spherical terrain':'可编辑的球面地形',
  'Left drag paints. Right or Alt-drag rotates. Wheel zooms. Use this toggle to rotate with touch.':'绘制模式下左键拖动绘图，右键或 Alt 拖动旋转，滚轮缩放；触屏可切换旋转模式。',
  'Paint: left drag · Rotate: right / Alt-drag · Zoom: wheel. Touch: toggle Drag mode.':'左键绘制；右键或 Alt 拖动旋转；滚轮缩放。触屏请切换拖动模式。',
  'Base sphere radius, independent of zoom. Mountain height stays the same.':'画面中的球体半径，与缩放独立；山脉显示高度保持不变。',
};

// Longer explanatory notes use whole translations rather than word swapping.
const notes=[
  ['Physical radius is independent','物理半径与画面球体半径、缩放分别控制。'],
  ['Fixed solar mass and luminosity','固定太阳质量与光度，采用圆轨道。季节相位 0° 为北半球春分，90° 为夏至。'],
  ['Calibrated elevations before artistic folds','使用装饰性褶皱之前的标定高程；海底深度为估算值，海面显示在海平面。'],
  ['Global blackbody reference','全球黑体辐射参考值，不等于地表气温；温度模型另有有效发射率与热输送。'],
  ['Painting pauses time.','绘制地形时暂停模拟。隐藏页面后需点击播放继续。重置地形会清除绘制内容及已应用的侵蚀。'],
  ['Generate ice, vegetation, temperature','无需播放即可生成当前日期的冰雪、植被、气温、降雨与风场；更改季节、倾角或地形会重新生成，播放则继续演化。'],
  ['Terrain, ice, vegetation and continuous','地形、冰雪、植被与连续河网在同一视图呈现。地表覆盖与河网由气候估算；湿度、降雨和融雪影响河宽。播放可继续演化，环境对比可查看水量和能量守恒。'],
  ['Ready without Play:','无需播放：纬度、季节、海陆与海拔共同生成日均参考气候。播放后继续演化，海洋变化更慢。启用水循环后，冰雪反照率、相变能量与海洋热输送会反馈到气温；不模拟逐小时气温或气压。'],
  ['Emissivity is an effective','发射率是有效辐射参数，不是实测大气成分。热输送强度随半径平方的倒数缩放。'],
  ['Terrain, physical parameters and manual','改变地形、物理参数或手动修改时间，会在所选日期重新生成参考气候；相机和显示比例不会清空历史。参考气候是示意估算，不代表已达到平衡。可下载完整模拟保存运行状态。'],
  ['Rain, humidity and soil initialize','降雨、湿度与土壤按地理规律初始化，无需播放。初始通量为估算值，播放后使用守恒的蒸发、水汽输送、凝结和汇流计算。蒸发降温，凝结升温；降雪蓄积，受能量限制的融雪进入地表径流。不模拟地下水或天气预报。'],
  ['Precipitation includes liquid rain','降水包括液态雨与实际转移到陆地的雪。降雪按全球面积折算毫米水当量，取自最近一步；播放前或旧存档缺少相态时暂无数据。储量包括海洋，流出量表示气候网格之间的实际转移，与参考河网的显示宽度不同。'],
  ['Upwind sea and terrain shape','上风向的海洋与地形影响初始降雨，后续降雨由水循环计算。动态环流可扩展季节性风带；闭流洼地先蓄水，再溢流。海洋初始深度决定有限储水量。'],
  ['Enabling water or changing its','启用水循环或修改参数，会在当前时刻重新开始温度和水循环演化。绘制地形、修改物理参数和手动修改时间也会重启；地形保持不变。'],
  ['Generate climate initializes all','生成气候会立即初始化各系统；播放后演化冰雪、潜热、海流与植被。修改参数时，环境对比仍保留已采集的基准。'],
  ['Temperature contrasts drive bounded','温差结合自转与地表阻力驱动有界风场扰动。封闭海流在约五天内响应风场；切换模式会重新生成气候。风与海流图显示相应矢量，不模拟气压和深海。'],
  ['Soft white cloud cover','白色云层跟随大气水汽变化，播放时演化、暂停时静止；只影响显示，不改变气候或水量。'],
  ['Vegetation responds to','植被在多年尺度上响应气温、降雨与土壤湿度，并反馈到气候；不模拟物种或碳循环。'],
  ['Snow and ice reflect','冰雪反射更多阳光，改变地表吸收的能量及后续气温。'],
  ['Ice sheets use the climate','冰盖使用气候网格，无法分辨狭窄山谷冰川。气候生成或观测导入的初始冰量都来自已有储水；积雪约三十年压实。冰流与融化使用播放时间。侵蚀面板可采集并应用冰川侵蚀；导入浮冰架使用独立守恒库存，不模拟崩解或移动冰面几何。'],
  ['Mesh routing uses the same','地形汇流沿用同一套地表储水。地球地表结合参考河网、冰雪、植被、湖岸与湿地；河宽随湿度、降雨和融雪变化，并为易读性作了夸张。地表查看可检查真实蓄水转移；切换模式会重新生成气候。'],
  ['Stores use global mm','储量按全球面积折算为毫米水当量。融雪进入地表径流，可采集为侵蚀输入。海洋热输送在封闭海洋网格回路中进行；动态模式响应风场，经典模式采用预设环流。下载完整模拟可保留这些状态、开关和对比历史。'],
  ['Capture the current water discharge','采集当前水流后，可按独立的地质年数演化河流侵蚀与坡面变化。冰川磨蚀在播放期间积累，采集冰川侵蚀可导入这段历史；干燥网格仍可能发生坡面平滑。'],
  ['Illustrative, uncalibrated coefficients','系数为尚未标定的示意参数。下切速率采用流量平方根与坡度的乘积；假定体密度一致，不模拟抬升和压实。更改这些参数会清空预览。'],
  ['Preview retains source climate','预览保留原气候与参考河网。应用后保存高度变化、重建河流并重启环境，结果可能与预览略有差异；高度限定在地形范围内。搬运中及入海沉积物仅记入报告，不作为向细网格的守恒转移。新采集会开始新的守恒统计，绘制地形或重置环境会清空预览。'],
  ['Complete simulation saves terrain','完整模拟保存地形、气候、水、冰雪、植被、时间、参数及对比历史（最大 32 MiB），恢复后暂停在存档时刻。仅地形文件最大 8 MiB，载入后气候关闭。两者均不包含未应用的侵蚀预览及撤销历史；准备期间编辑或推进时间会取消载入。'],
  ['Captured accumulated glacial abrasion','已采集累计冰川磨蚀与沉积。应用后保存候选地形并重启气候；演化地形则继续加入独立的河流与坡面模型。'],
  ['Maps are geographic estimates','地图是从守恒网格细化的地理估算。初始冰厚可来自观测导入；后续冰雪厚度由水量模型演化。陆冰流动使用粗气候网格，不模拟海冰漂移。极区百分比相对当地海洋面积计算，南北极不必相等。改变地形、日期或物理参数会重新生成状态；已采集基准保留至下次替换，历史最多记录本轮的 240 个样本。'],
  ['Grounded ice: 0 dark','陆冰厚度：0 米为深色，1,500 米为白色。地理细化估算无法分辨狭窄冰川。'],
  ['Natural cover colors','自然地表颜色：亮白为陆地积雪，蓝白为海冰。'],
  ['Temperature: −50 °C','气温：−50 °C 蓝色 → 0 °C 浅色 → +50 °C 红色；超出范围时颜色饱和。'],
  ['Land snow: 0 dark','陆地积雪：0 为深色，150 毫米水当量为白色；更高值颜色饱和。'],
  ['Sea ice: 0 dark','海冰：0 米为深色，2 米为白色；更高值颜色饱和。'],
  ['Land vegetation: 0 bare','陆地植被：0% 为裸地棕色，100% 为绿色。'],
  ['Arrows point with the captured','箭头指向采集时的表层流动方向。长度相对各图最大流速缩放，绝对最大值可在表格中比较。'],
  ['Estimated surface wind:','估算地表风：箭头指向流动方向，深蓝至绿色对应 0–30 米/秒。采用地理环流模板，不是气压求解器。'],
  ['Capture current water in Erosion','请在「侵蚀与沉积」中采集当前水流以开始预览。'],
  ['Net bed change:','净地形变化：−100 米为蓝色，0 为米色，+100 米为红色；超出范围颜色饱和。粗网格预览保留原气候及参考河网。'],
  ['Soil moisture:','土壤湿度：容量的 0–100%，由棕色至绿色；海洋为蓝色，数值按陆地面积计算。'],
  ['Temperature: −80 °C','气温：−80 °C 为蓝色，0 °C 为米色，+60 °C 为红色。暂停时即可生成日均参考气候，播放后继续演化，超出范围颜色饱和。'],
  ['Day / night ·','昼夜：夜间适度提亮以便编辑；夜面接收的太阳辐射仍为 0 W/m²。'],
  ['Terrain editing ·','地形编辑：改变物理设置会保留现有地形。'],
  ['Rapid spin:','自转过快，球形重力与海平面近似的精度下降。'],
  ['Terrain is large relative','地形高度相对行星半径过大，球面诊断结果仅为近似。'],
  ['Daily mean unavailable for slow','自转过慢或同步自转时（日长超过年长的 1/20），日均气候模型不可用。'],
];

const fragments={
  'global mm/day':'全球毫米/天',
  ...Object.fromEntries(['Perennial ice / snow','Tundra','Boreal forest','Temperate forest','Grassland / steppe','Desert','Savanna','Tropical seasonal forest','Tropical rainforest','Barren ground'].map(key=>[key,labels[key]])),
  'Grounded ice':'陆地冰川',
  'Generated reference climate — no Play needed':'参考气候已生成，无需播放','Evolving from generated climate':'从生成的气候继续演化',
  'Daily-mean model':'日均温度模型','speed limited by stable heat steps':'速度受稳定温度步长限制','energy residual':'能量残差','field lag':'场滞后',
  'generated initial flux estimates — no elapsed time':'初始通量估算，尚未推进时间','fluxes from the latest simulated step':'最近一步的通量',
  'equal-area cells':'等面积网格','min shared step':'分钟共用步长','min step':'分钟步长','cells':'网格',
  'sampled at day':'采样于第','Spin ':'自转 ','season ':'季节 ','Sun latitude ':'太阳直射纬度 ',
  'Cloud cover off · enable water, then select Planet surface':'云层已关闭；启用水循环并选择地球地表可显示云层',
  'Cloud cover ':'云量 ','Evolving circulation':'动态环流','Seasonal wind template / prescribed ocean gyres':'季节风模板 / 预设海洋环流',
  'max wind ':'最大风速 ','thermal perturbation ':'温差扰动 ','current ':'海流 ',
  'Enable water to evolve circulation':'启用水循环后可演化环流','Grounded ice flow off':'陆冰流动已关闭',
  'global mm water equivalent':'全球毫米水当量','max thickness ':'最大厚度 ','solid residual ':'固体残差 ','speed ':'速度 ',
  ' limited flow edges. Speed is capped at 20 km/yr; model coefficients are illustrative.':' 条流动边受限。速度上限为每年 20 千米，模型系数为示意值。',
  'Terrain routing':'地形汇流',' reservoirs':' 个蓄水单元','max standing depth ':'最大积水深度 ','max transfer ':'最大转移流量 ',
  'unresolved coast storage ':'未解析海岸储水 ',
  'Planet surface shows continuous climate-fed channels with exaggerated widths; inspect reports actual reservoir transfers. Lake shores are approximate.':'地球地表显示连续气候河网，河宽经夸张；地表查看给出实际蓄水转移，湖岸为近似重建。',
  'Elevation imported from ':'高程来源：','(ice surface), sampled to mesh.':'（冰面高程），已采样到网格。',
  'Imported heights retained; no erosion applied.':'保留导入高程，尚未应用侵蚀。',
  'Save failed: ':'保存失败：','Load failed: ':'载入失败：',
  'Generated at zero age — Play is not required.':'初始状态已生成，无需播放。',
  'Evolving with conservative water and energy budgets.':'正在按水量和能量守恒演化。',
  ' Baseline is fixed until you capture again.':' 基准保持不变，直到再次采集。',
  'Environment unavailable. Showing the last captured state; enable water and a supported rotation.':'环境暂不可用，显示上次采集状态；请启用水循环并使用支持的自转速度。',
  'Day ':'第 ',' · age ':' · 演化时间 ','tilt ':'倾角 ',' · vegetation ':' · 植被 ','ice albedo ':'冰雪反照率 ',
  'on':'开启','off':'关闭',
  'Global temperature':'全球气温','Ocean ice cover':'海洋冰覆盖率','Land snow cover':'陆地积雪覆盖率',
  'North polar ocean ice (>60°)':'北极区海冰（北纬 60° 以北）','South polar ocean ice (<−60°)':'南极区海冰（南纬 60° 以南）',
  'Vegetation cover':'植被覆盖率','Mean albedo':'平均反照率','Snow inventory':'积雪储量','Sea-ice inventory':'海冰储量',
  'Grounded ice inventory':'陆冰储量','Maximum ice speed':'最大冰流速度','Glacial solid residual':'冰川固体残差',
  'Snow / land-ice melt':'积雪 / 陆冰融化','Precipitation':'降水','Maximum current':'最大海流速度',
  'Water budget residual':'水量残差','Total enthalpy residual':'总焓残差','% ocean':'% 海洋面积','% land':'% 陆地面积',
  'global equivalent':'全球当量','global mm':'全球毫米','global m':'全球米',
  '° lat, ':'° 纬度，','° lon':'° 经度','seafloor':'海底深度','elevation':'海拔',
  'solar time undefined at pole':'极点无定义太阳时','h local solar time':'时当地太阳时','°C daily-mean cell':'°C 网格日均气温',
  'estimated wind E ':'估算风速：向东 ',' / N ':' / 向北 ','potential cover: ':'潜在地表：',
  'local surface estimate ':'当地地表估算 ','annual mean ':'年均 ','mm per Earth year':'毫米/地球年',
  'local air ':'当地空气估算 ','local surface ':'当地表面估算 ','ice shelf ':'浮冰架 ',
  'local ice / water estimate ':'当地冰水估算 ','column saturation proxy ':'水汽柱饱和度近似 ',
  'cloud display ':'云量显示 ','liquid precipitation ':'液态降水 ',' / land snowfall ':' / 陆地降雪 ',
  'mm/day per whole cell':'毫米/天（整个网格）','rain/snow phase unavailable':'暂无雨雪相态',
  'current column at day ':'当前气柱时间：第 ','precipitation ':'降水 ',
  'total precipitation ':'总降水 ','generated initial estimate':'初始生成估算','latest simulated-step rate':'最近一步的速率',
  'coarse-cell land snow ':'粗网格陆地积雪 ',' / melt ':' / 融雪 ',' / ocean ice ':' / 海冰 ',
  'cell outflow ':'网格流出量 ','grounded ice cell ':'网格陆冰 ',' / flow ':' / 流速 ',
  'nearest terrain reservoir: mean depth ':'最近地形蓄水单元：平均水深 ',' / outflow ':' / 流出量 ',
  'bed change ':'地形变化 ','mobile sediment ':'搬运中沉积物 ','mm whole-cell equivalent':'毫米（全网格当量）',
  'terrain preview':'地形预览','per land area':'按陆地面积','soil ':'土壤 ','standing ':'积水 ',
  'baseline → current:':'基准 → 当前：','grounded ice ':'陆冰 ','vegetation ':'植被 ','sea ice ':'海冰 ','snow ':'积雪 ','ice ':'冰 ',
  'ocean':'海洋','Frozen ':'固定采集：','generated initial discharge estimate':'初始生成流量估算',
  'latest-step discharge':'最近一步流量','from day ':'采集于第 ','; not a yearly average. Max ':'天，并非年平均值。最大 ',
  'Stable step ':'稳定步长 ','; ≤32 per click.':'；每次最多 32 步。',
  'Request is below the stable step (':'请求时长小于稳定步长（', ' yr); increase years per click.':' 年）；请增加单次年数。',
  'Solar energy: ':'太阳辐射：',' W/m² · dark blue → teal → orange. Colors retain terrain shading.':' W/m²；深蓝 → 青色 → 橙色，保留地形明暗。',
  'Precipitation: ':'降水：',' mm/day · dark blue → cyan → cream. ':' 毫米/天；深蓝 → 青色 → 米色。',
  'Generated initial estimate':'初始生成估算','Latest simulated-step rate':'最近一步的速率','Latest simulated-step transfer':'最近一步的转移量',
  '; higher values saturate.':'；更高值颜色饱和。','Cell surface outflow: ':'网格地表流出量：',
  ' m³/s · dark blue → cyan, log scale. ':' m³/s；深蓝 → 青色，对数色标。',
  'Planet surface channel widths are climate-fed estimates.':'地球地表河宽是根据气候估算的显示值。',
  'Advanced ':'已推进 ',' yr in ':' 年，共 ',' steps.':' 步。',' Work limit reached; click again to continue.':' 已达到本次计算上限，再次点击可继续。',
  'Applied ':'已应用 ',' geological yr from source day ':' 个地质年，水流来源时间为第 ',
  ' triangles clipped. Report only: ':' 个三角形已限幅。仅记录于报告：',
  ' km³ mobile / ':' km³ 搬运中 / ',' km³ ocean sediment.':' km³ 入海沉积物。',
};
const substitutions=Object.entries(fragments).sort((a,b)=>b[0].length-a[0].length).map(([en,zh])=>[
  new RegExp((/^[A-Za-z]/.test(en)?'(?<![A-Za-z])':'')+en.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+(/[A-Za-z]$/.test(en)?'(?![A-Za-z])':''),'g'),zh]);

const parameters={planet:'行星',orbit:'轨道',thermal:'温度模型',water:'水循环',environment:'环境',
  radiusM:'半径（米）',densityKgM3:'密度（千克/立方米）',reliefM:'陆地高程尺度（米）',oceanDepthM:'深度（米）',
  siderealPeriodS:'恒星日（秒）',retrograde:'逆向自转',obliquityRad:'自转轴倾角（弧度）',distanceM:'轨道距离（米）',
  bondAlbedo:'邦德反照率',spinPhaseRad:'自转初相位（弧度）',orbitPhaseRad:'公转初相位（弧度）',emissivity:'有效发射率',
  landHeatCapacity:'陆地热容量（J/m²/K）',diffusion:'热输送系数',evaporationFraction:'蒸发能量比例',soilCapacityKgM2:'土壤容量（千克/平方米）',
  initialOceanDepthM:'初始海洋水深（米）',windMps:'风带强度（米/秒）',moistureDiffusivityM2s:'水汽混合系数（m²/s）',
  routingSpeedMps:'地表流速（米/秒）',oceanStrengthMps:'海流强度（米/秒）',vegetation:'植被反馈',iceAlbedo:'冰雪反照率反馈',
  terrainWater:'地形汇流',glaciers:'陆地冰川',dynamicCirculation:'动态环流'};

export function translate(text) {
  const trimmed=text.trim();if(!trimmed)return text;
  if(trimmed.startsWith('{')&&trimmed.includes('"planet"')) {
    try {
      return Object.entries(JSON.parse(trimmed)).map(([group,values])=>parameters[group]+'\n'+Object.entries(values)
        .filter(([key])=>key!=='schemaVersion').map(([key,value])=>'  '+(parameters[key]??key)+'：'+(typeof value==='boolean'?(value?'开启':'关闭'):value)).join('\n')).join('\n\n');
    } catch { /* Non-parameter text stays readable if a future format changes. */ }
  }
  if(Object.hasOwn(labels,trimmed))return text.replace(trimmed,labels[trimmed]);
  if(trimmed.startsWith('About '))return translate(trimmed.slice(6))+'说明';
  for(const [start,zh] of notes)if(trimmed.startsWith(start))return zh+(trimmed.includes('Clouds:')?' 云量采用水汽柱饱和度近似：70–100% 饱和度对应 0–100% 云覆盖，不透明度最高 66%；不是实测湿度或三维云水。':'');
  let result=text;
  for(const [pattern,zh] of substitutions)result=result.replace(pattern,zh);
  return result.replace(/\bmm\/day\b/g,'毫米/天').replace(/\bm\/yr\b/g,'米/年')
    .replace(/(\d) to (?=[−\-\d])/g,'$1 至 ').replace(/\bmin\b/g,'分钟')
    .replace(/(?<=\d) d\b/g,' 天').replace(/(?<=\d) h\b/g,' 小时').replace(/(?<=\d) yr\b/g,' 年');
}
